Korzystając z następującego array'a:

In [5]:
import numpy as np

In [6]:
np.random.seed(1337)
x = np.round(np.random.normal(size=30), 2)
y = x + np.round(np.random.normal(size=30) * 0.1, 2)
x

array([-0.7 , -0.49, -0.32, -1.76,  0.21, -2.01, -0.56,  0.34,  1.55,
       -1.37,  1.43, -0.28, -0.56,  1.19,  1.7 , -1.69, -0.7 ,  0.58,
        0.98, -1.22, -1.33, -0.  , -1.31, -0.38,  1.27,  0.12,  0.15,
       -2.75, -0.36,  0.01])

Wyznacz/policz:

1) Średnią z `x`

In [7]:
np.average(x)

-0.2753333333333333

2) Sumę `x`

In [8]:
x.sum()

-8.26

3) Średnią z wartości bezwzględnych z `x`

In [9]:
np.average(np.abs(x))

0.9106666666666666

4) Element najbardziej odległy od $0$ z `x`

In [10]:
x[np.argmax(np.abs(x))]


-2.75

5) Element najbardziej odległy od $2$ z `x`

In [24]:
x[np.argmax(np.abs(x-2))]

-2.75

6) Array który ustawi elementy mniejsze od $-1$ na $-1$, a większe od $1$ na $1$

In [25]:
np.clip(x, -1, 1)

array([-0.7 , -0.49, -0.32, -1.  ,  0.21, -1.  , -0.56,  0.34,  1.  ,
       -1.  ,  1.  , -0.28, -0.56,  1.  ,  1.  , -1.  , -0.7 ,  0.58,
        0.98, -1.  , -1.  , -0.  , -1.  , -0.38,  1.  ,  0.12,  0.15,
       -1.  , -0.36,  0.01])

7) Średni błąd między (ERR) `x` i `y`

In [26]:
(x - y).mean()

-0.005333333333333344

8) Średni błąd bezwzględny (MAD) między `x` i `y`

In [27]:
np.mean(np.abs(x - y)) # MAE (Mean absolute error)

0.08266666666666665

9) Średni błąd kwadratowy (MSE) między `x` i `y`

In [28]:
(np.square(x -y)).mean()

0.009780000000000002

10) Pierwiastek ze średniego błędu kwadratowego (RMSE) między `x` i `y`

In [29]:
np.sqrt((np.square(x - y)).mean())

0.09889388252060893

11) Napisz funkcję `standardize(X)`, która unormuje każdą kolumnę macierzy `X` (każdą oddzielnie).
Średnia z każdej kolumny powinna być równa $0$, a odchylenie standardowe równe $1$.
Jest to procedura bardzo często stosowana w MLu.

In [151]:
def standardize(x):
    new_x = np.empty(x.shape)
    for column in range(x.shape[1]):
        new_column = (x[:, column]-x[:, column].mean())/np.std(x[:, column])
        new_x[:, column] = new_column
        
    return new_x   

Przykładowa macierz do sprawdzenia:

In [152]:
z = np.array([[1, 10], [2, 9], [3, 8], [4, 7], [5, 6], [6, 5]])
z

array([[ 1, 10],
       [ 2,  9],
       [ 3,  8],
       [ 4,  7],
       [ 5,  6],
       [ 6,  5]])

In [153]:
new_z = standardize(z)
new_z

array([[-1.46385011,  1.46385011],
       [-0.87831007,  0.87831007],
       [-0.29277002,  0.29277002],
       [ 0.29277002, -0.29277002],
       [ 0.87831007, -0.87831007],
       [ 1.46385011, -1.46385011]])

In [154]:
for i in range(new_z.shape[1]):
    print(new_z[:, i].mean(), new_z[:, i].std())

-3.700743415417188e-17 1.0
3.700743415417188e-17 1.0
