Ile wynosi liczba $6.0*10^{24} + 1000$ według pythona?

In [35]:
6.0*10**24 + 1000

6e+24

W jaki sposób z wektora x można wybrać elementy pomiędzy $10$ a $42$?

In [36]:
import numpy as np

In [37]:
x = np.array([3, 10, 14, 6, 44, 67, 34, 27, 88])
x

array([ 3, 10, 14,  6, 44, 67, 34, 27, 88])

In [38]:
x[(10 < x) & (42 > x)]

array([14, 34, 27])

In [39]:
x[(x > 10) & (x < 42)]

array([14, 34, 27])

Jaki jest dtype elementów arraya `x=np.array([1, 1.0, '1.0'])`?

In [40]:
x = np.array([1, 1.0, '1.0'])
x

array(['1', '1.0', '1.0'], dtype='<U32')

Ile wynosi wynik takiego działania (policz  w numpy)? <br/>
$x*M*x^T = ?$

In [41]:
M = np.array([[1, -2, 3, 4], [-2, 4, 6, 8], [3, 6, 8, -12], [4, 8, -10, 16]])
x = np.array([42, 1, 32, -5])
M, x

(array([[  1,  -2,   3,   4],
        [ -2,   4,   6,   8],
        [  3,   6,   8, -12],
        [  4,   8, -10,  16]]),
 array([42,  1, 32, -5]))

In [42]:
np.matmul(np.matmul(x, M), x.transpose())

20400

Ile wynosi całka oznaczona (pole pod wykresem) od $-2$ do $2$ z funkcji $f(x) = exp(-x^2)$? Wynik podaj z dwoma miejscami po przecinku. Do obliczeń wykorzystaj tzw. symulację Monte Carlo. Wykonaj 10_000_000 symulacji. Pomoc patrz koniec prezentacji.

In [34]:
import random


def func(x):
    return np.exp(-x**2)


def monte_carlo(a, b, n):
    """
    calculates integral using Monte-Carlo method
    """
    sum = 0
    for _ in range(n):
        u = random.uniform(0, 1)
        x_i = a + (b - a) * u
        sum += func(x_i)
    return ((b - a) / n) * sum


if __name__ == "__main__":
    a = -2
    b = 2
    results = []
    given_n = 10_000_000

    results = round(monte_carlo(a, b, given_n), 2)

    print(results)

1.76
